### ISSUE TITLE
add a pipeline to promote images from the dev -> staging/production registry

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/issues#26]
we need a nice way to be able to build images in dev then promote to a staging/production registry for promotion.

One simple way could be a new trigger in the staging/production repository which takes a canonical YAML file with a list of images and from / to registries.

Then a single step in the pipeline could use a step like [skopeo](https://github.com/containers/skopeo) to copy each image from the source -> destination registry

e.g. a file like this...

```yaml
# .jx/images.yaml
registries:
  from: gcr.io/myproject
  to: 
  - gcr.io/another-project
  images:
  - mythingy:1.2.3
  - another:4.5.6.
```
